name: Deploy NestJS to Azure App Service

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy source to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: tesis-back-benj2024
          package: .
